# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

env:
  DISPLAY: ":99"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Setup headless environment for GUI logic
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Build with Maven
        run: cd maven/chessapp && mvn -B package --file pom.xml
